run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - copyloopvar
    - gocritic
    - gosec
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment
  
  gofmt:
    simplify: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam
  
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input
  
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - unparam
        - govet
    
    # Exclude known linters from partially hard-coded issues
    - linters:
        - gosec
      text: "G404:" # Use of weak random number generator

  max-issues-per-linter: 50
  max-same-issues: 3
  new: false






